INSERT INTO companies (iata_code, name) VALUES ('AA', 'American Airlines');
INSERT INTO companies (iata_code, name) VALUES ('OO', 'SkyWest Airlines');
INSERT INTO companies (iata_code, name) VALUES ('MQ', 'Envoy Air');
INSERT INTO companies (iata_code, name) VALUES ('DL', 'Delta Air Lines');
INSERT INTO companies (iata_code, name) VALUES ('9E', 'Endeavor Air');
INSERT INTO companies (iata_code, name) VALUES ('UA', 'United Airlines');
INSERT INTO companies (iata_code, name) VALUES ('G4', 'Allegiant Air');
INSERT INTO companies (iata_code, name) VALUES ('AS', 'Alaska Airlines');
INSERT INTO companies (iata_code, name) VALUES ('F9', 'Frontier Airlines');
INSERT INTO companies (iata_code, name) VALUES ('B6', 'JetBlue Airways');
INSERT INTO companies (iata_code, name) VALUES ('WN', 'Southwest Airlines');
INSERT INTO companies (iata_code, name) VALUES ('HA', 'Hawaiian Airlines');
INSERT INTO companies (iata_code, name) VALUES ('OH', 'PSA Airlines');
INSERT INTO companies (iata_code, name) VALUES ('NK', 'Spirit Airlines');
INSERT INTO companies (iata_code, name) VALUES ('YX', 'Republic Airways');